services:
    search:
        image: getmeili/meilisearch:v1.8
        volumes:
            - ./meili_data:/meili_data
        ports:
            - 7700:7700
        environment:
            MEILI_ENV: development
            MEILI_MASTER_KEY: ${MEILISEARCH_KEY}
            MEILI_NO_ANALYTICS: 'true'
